spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/my_ticket_service_db
    username: user
    password: password
app:
  updateUserAndCreateTicketEnabled: true
  createDataSource: true